# Generated by Django 4.1.2 on 2022-10-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construyeya', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorio',
            new_name='Categoria',
        ),
    ]
