# Generated by Django 4.1.1 on 2022-10-07 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construyeya', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAgencia', models.CharField(max_length=150, unique=True)),
                ('direccionAgencia', models.CharField(max_length=150)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construyeya.producto')),
            ],
        ),
    ]
