# Generated by Django 4.1.1 on 2022-10-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construyeya', '0004_agencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='producto',
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrega', models.DateTimeField()),
                ('direccionEntrega', models.CharField(max_length=100)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construyeya.agencia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construyeya.producto')),
            ],
        ),
    ]
