# Generated by Django 4.1.1 on 2022-10-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construyeya', '0005_remove_agencia_producto_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fechaEntrega',
            field=models.DateField(),
        ),
    ]
